
language: cpp

os: linux
dist: trusty
compiler: gcc
services: docker

cache: ccache

env:
  global:
    - DOCKER_OPTS="--rm -ti -v ${HOME}/.ccache:/root/.ccache -v ${TRAVIS_BUILD_DIR}:/build -w /build"
  matrix:
    # Latest Boost, gcc
    - DOCKER_IMAGE=lballabio/quantlib-devenv:rolling
      CACHEDCC="ccache gcc" CACHEDCXX="ccache g++"
      CXXFLAGS="-O2 -std=c++11 -Wall -Wno-unknown-pragmas -Werror"
    # Latest Boost, clang
    - DOCKER_IMAGE=lballabio/quantlib-devenv:rolling
      CACHEDCC="ccache clang" CACHEDCXX="ccache clang++"
      CXXFLAGS="-O2 -std=c++11 -Wall -Wno-unknown-pragmas -Werror"

before_install:
  - docker pull ${DOCKER_IMAGE}
  - git fetch origin master:master
  - git merge --no-edit master || exit

script:
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ./autogen.sh
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ./configure --disable-static --enable-std-classes CC="${CACHEDCC}" CXX="${CACHEDCXX}" CXXFLAGS="${CXXFLAGS}"
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ccache --zero-stats
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ccache --max-size=2.5G
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ccache --show-stats
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} make -j 2
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ccache --show-stats
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ./test-suite/quantlib-test-suite --log_level=message -- --faster

